app:
  baseurl: http://localhost:8083/wms
  lsemu:
    baseurl: http://localhost:8082/lsemu/api/v1/lsemu
server:
  port: 8083
  servlet:
    context-path: /wms
  forward-headers-strategy: framework
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api.html
    tags-sorter: alpha
    operations-sorter: alpha
    disable-swagger-default-url: true
management:
  server:
    port: 9093
  health:
    mongo:
      enabled: true
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/leswms
      repositories:
        type: auto