app:
  baseurl: https://localhost:8081/wms
server:
  port: 8081
  servlet:
    context-path: /wms
  forward-headers-strategy: framework
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api.html
    tags-sorter: alpha
    operations-sorter: alpha
    disable-swagger-default-url: true
management:
  server:
    port: 9090
  health:
    mongo:
      enabled: true
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/leswms
      repositories:
        type: auto